---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  database_url: "http://my-database-url.com"
  app_mode: "production"


----
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  database_password: bXktc2VjdXJlLXBhc3N3b3Jk  # base64-encoded "my-secure-password"

---
apiVersion: v1
kind: Pod
metadata:
  name: my-app-pod
spec:
  containers:
    - name: my-app
      image: my-app-image
      env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: database_url
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: database_password
